### ISSUE TITLE
提示：Binary does not exist

### ISSUE THREAD

**Issue by yujiak** [ibrandcc/laravel-miniprogram-poster#1]
use iBrand\Miniprogram\Poster\MiniProgramShareImg;
    
$url = 'https://www.ibrand.cc/';
$result = MiniProgramShareImg::generateShareImage($url);

直接使用这段代码也提示：Binary does not exist

**Comment by tangqi198707** [comment]
将 phantomjs 加入环境变量

**Comment by yujiak** [comment]
配置环境变量后，使用 MiniProgramShareImg::generateShareImage($url)变得非常慢(基本就是打不开这个页面了)，端口也被一直占用，导致项目的其他任何页面都打不开了，请问这个是怎么回事呢

**Comment by chenbidepro** [comment]
> 配置环境变量后，使用 MiniProgramShareImg::generateShareImage($url)变得非常慢(基本就是打不开这个页面了)，端口也被一直占用，导致项目的其他任何页面都打不开了，请问这个是怎么回事呢

我们暂时没有发现这种问题，目前该包稳定在我们生产环境运行中。

Binary does not exist  这个问题主要是在系统环境中无法发现 phantomjs 导致的。

**Comment by gold3bear** [comment]
https://github.com/anam-hossain/phantommagick/issues/10

**Comment by Joycezhangw** [comment]
设置了环境变量，或者软链接。都是无效的
