### ISSUE TITLE
请问下没有指定字体的，但是生成的图片中文都不显示

### ISSUE THREAD

**Issue by phpcxy** [ibrandcc/laravel-miniprogram-poster#4]
如题。

**Comment by tangqi198707** [comment]
不一定非要指定字体的，除非需要特殊字体，才要安装，有没有检查过样式，兼容性问题呢？

**Comment by tangqi198707** [comment]
PhantomJS 实现的浏览器兼容性比较差，遇到过样式问题，但是没有遇到过你这样的问题，建议从这方面检查一下

**Comment by phpcxy** [comment]
可能是系统没有中文字体的缘故。我的ubuntu16.04，CSS样式指定了中文是雅黑，然后手动安装了个微软雅黑解决了。不过有一些样式兼容性的确有些差异。
